interfaces_ether_interfaces:
  - device: eth0
    bootproto: static
    address: "{{ ansible_host }}"
    netmask: 255.255.255.0
    network: 10.81.100.0
    broadcast: 10.81.100.255
    gateway: 10.81.100.1
    dnsnameservers: 10.80.100.21 10.80.100.22 10.80.100.23
    dnssearch: jumia.local