---
- name: This playbook is for setup the dashboard machines
  hosts: mkt-portal
  # TODO: The packages needs to be updated before of any task or role
  roles:
    - { role: common, common_hostname: "{{ inventory_hostname }}"}
    - { role: users, tags: ['add-users'] }
    - network
    - mkt-portal
