---
- name: This playbook is for setup the XCally machines
  hosts: XCally
  # TODO: The packages needs to be updated before of any task or role

  roles:
    - { role: users, tags: ['add-users'] }

  tasks: 
    - name: Update all packages to the latest version
      apt: upgrade=dist
    
    