---
- name: Install Zabbix Agent 2
  hosts: all
  become: true
  roles:
      - zabbix_agent
  vars:
      zabbix_agent_version: 5.4
      zabbix_agent2_logtype: file
      zabbix_agent2_logfile: /var/log/zabbix/zabbix_agent2.log
      zabbix_agent2_logfilesize: 1
      zabbix_agent2_debuglevel: 2
      zabbix_agent_server: russian.jumia.local
      zabbix_agent2_listenport: 20050
      zabbix_agent_serveractive: russian.jumia.local
      zabbix_agent2_hostnameitem: system.hostname
      zabbix_agent2_hostmetadataitem: system.uname
      zabbix_agent2_controlsocket: /tmp/agent.sock
